### ISSUE TITLE
Error in py_call_impl

### ISSUE THREAD

**Issue by nlubock** [ropenscilabs/umapr#25]
Hello,

I'm trying to get umapr to work on the iris example, but every time I run it, I get the following error:

```
library(umapr)
library(tidyverse)
df <- as.matrix(iris[ , 1:4])
embedding <- umap(df)

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: __init__() got an unexpected keyword argument 'alpha'
```

I followed the python install instructions from the umap GitHub and I'm able to `import umap` just fine in python.

Here's my session info:

```
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.4

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.2.0    stringr_1.2.0    dplyr_0.7.4      purrr_0.2.4      readr_1.1.1      tidyr_0.7.2     
 [7] tibble_1.3.4     ggplot2_2.2.1    tidyverse_1.2.1  umapr_0.0.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14     cellranger_1.1.0 plyr_1.8.4       bindr_0.1        tools_3.3.3      lubridate_1.7.1 
 [7] jsonlite_1.5     nlme_3.1-131     gtable_0.2.0     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.4     
[13] psych_1.7.8      cli_1.0.0        rstudioapi_0.7   yaml_2.1.14      parallel_3.3.3   haven_1.1.0     
[19] bindrcpp_0.2     xml2_1.1.1       httr_1.3.1       hms_0.3          grid_3.3.3       reticulate_1.4  
[25] glue_1.2.0       R6_2.2.2         readxl_1.0.0     foreign_0.8-69   modelr_0.1.1     reshape2_1.4.3  
[31] magrittr_1.5     scales_0.5.0     rvest_0.3.2      assertthat_0.2.0 mnormt_1.5-5     colorspace_1.3-2
[37] stringi_1.1.5    lazyeval_0.2.1   munsell_0.4.3    broom_0.4.2      crayon_1.3.4 
```

**Comment by seaaan** [comment]
Thanks for letting us know. It looks like `alpha` is no longer an argument to `UMAP`, and we're providing it by default, so that's why it's failing. I will try to fix this in the next couple of days. 

I would suggest using https://cran.r-project.org/web/packages/umap/index.html which is a separate package by a different author, which provides both the Python wrapper functionality we provide here and a separate, pure R implementation. It will probably be better supported going forward.

**Comment by seaaan** [comment]
I believe this issue should be fixed. Please let me know if you have further issues.

**Comment by shabir-sm1406103** [comment]
HI,

Im still having this issue

> df <- as.matrix(iris[ , 1:4])
> embedding <- umap(df)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: __init__() got an unexpected keyword argument 'alpha'
> 


any fix for this?

**Comment by seaaan** [comment]
I suggest that you use a different UMAP R package. There are two and they provide more features than `umapr` does and they are more actively developed. These packages are:

-   [umap](https://github.com/tkonopka/umap), which provides the same Python wrapping function as `umapr` and also an R implementation, removing the need for the Python version to be installed. It is available on [CRAN](https://cran.r-project.org/web/packages/umap/index.html).

-   [uwot](https://github.com/jlmelville/uwot), which also provides an R implementation, removing the need for the Python version to be installed.

**Comment by LuyiTian** [comment]
The R implementation works but really slow. The python version for `umap` still gives me the same error. I have everything up-to-date.

**Comment by seaaan** [comment]
Sorry to hear that! It sounds like you are using the `umap` package as I suggested. I would recommend reading this [vignette](https://cran.r-project.org/web/packages/umap/vignettes/umap_learn.html). If you still have that error, you could file an issue on the [github page](https://github.com/tkonopka/umap) for `umap` and hopefully they can help you there.

**Comment by TomKellyGenetics** [comment]
I'm trying to run benchmarking on this package against the others and still get this error message. Is there any intention to get it fixed?
